name:                syzygy
version:             0.1.0.0
homepage:            https://github.com/sleexyz/syzygy#readme
license:             BSD3
author:              Sean Lee
maintainer:          freshdried@gmail.com
copyright:           BSD3
category:            Other
extra-source-files:
  - README.md

default-extensions:
  - DeriveFunctor
  - DuplicateRecordFields
  - GeneralizedNewtypeDeriving
  - NamedFieldPuns
  - OverloadedStrings
  - ScopedTypeVariables
  - TypeApplications
  - ViewPatterns
  - MultiParamTypeClasses
  - RankNTypes


dependencies:
  - base >= 4.7 && < 5
  - profunctors
  - vivid-osc
  - bytestring
  - time
  - network
  - alsa-core
  - alsa-seq
  - foreign-store

library:
  source-dirs: src

executables:
  syzygy-live:
    source-dirs: src
    main: main.hs

tests:
  syzygy-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - syzygy
      - hspec
      - hspec-expectations
      - QuickCheck
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Werror -fno-warn-type-defaults -fno-warn-name-shadowing -Wno-unused-do-bind
